- name: Install memcached
  apt: pkg={{item}} state=installed
  with_items:
    - memcached

- name: Configure memcached
  lineinfile: dest=/etc/memcached.conf regexp=^-l line="-l 0.0.0.0"
  notify: restart-memcached

# force memcached to be reloaded *now* so services can use it
- meta: flush_handlers
