- include_vars: "{{ansible_os_family}}.yml"

- include: roles/common/deploy_pkg.yml pkg_name={{glance_pkg}}

- name: Setup glance service
  openstack_service: user={{glance_user}} password={{glance_pass}} type=image
                     description="OpenStack Image Service"
                     url="{{glance_private_api}}"
                     public_url="{{glance_public_api}}"
                     admin_password={{keystone_admin_pass}}
                     keystone_url="{{keystone_private_api}}"

- name: Add glance DB
  mysql_db: name=glance state=present
            login_host={{mysql_host}} login_user={{mysql_root_user}} login_password={{mysql_root_pass}}

- name: Add glance DB user
  mysql_user: name={{glance_db_user}} password={{glance_db_pass}} priv=glance.*:ALL state=present
              host=% login_host={{mysql_host}} login_user={{mysql_root_user}} login_password={{mysql_root_pass}}

# python-ceph can't really be built into venv (and doesn't exist in pip)
# so symlink in what glance needs
- name: Hack symlinks for python-ceph into venv
  file: src={{item}}
        dest=/srv/glance/lib/python2.7/site-packages/{{item.split('/')[-1]}} state=link
  with_items: "{{ceph_python_libs}}"
  notify:
    - restart-glance

- name: Configure glance-api.conf
  template: src=glance-api.conf dest=/etc/glance/
  notify: restart-glance

- name: Configure glance-registry.conf
  template: src=glance-registry.conf dest=/etc/glance/
  notify: restart-glance

- name: Run DB sync
  when: pkg_changed.changed
  command: /srv/glance/bin/glance-manage db sync
