- include_vars: "{{ansible_os_family}}.yml"

- include: roles/common/deploy_pkg.yml pkg_name={{nova_compute_pkg}}
- include: roles/common/deploy_pkg.yml pkg_name={{neutron_compute_pkg}}

# python-ceph can't really be built into venv (and doesn't exist in pip)
# so symlink in what glance needs
- name: Hack symlinks for python-ceph into nova venv
  file: src={{item}}
        dest=/srv/nova/lib/python2.7/site-packages/{{item.split('/')[-1]}} state=link
  with_items: "{{compute_python_libs}}"
  notify:
    - restart-nova

- name: Ensure the neutron server components aren't enabled
  service: name={{item}} enabled=no state=stopped
  with_items:
   - erp-neutron-dhcp-agent
   - erp-neutron-l3-agent
   - erp-neutron-metadata-agent

- name: Configure nova-compute
  template: src=nova-compute.conf dest=/etc/nova
  notify: restart-nova

- name: Configure nova
  template: src=nova.conf dest=/etc/nova
  notify: restart-nova

- name: Configure neutron.conf
  template: src=neutron.conf dest=/etc/neutron/
  notify: restart-neutron

- name: Configure openvswitch_agent.ini
  template: src=openvswitch_agent.ini dest=/etc/neutron/plugins/ml2/
  notify: restart-neutron

# HACK to make nova-compute work with EDK2
# nova-compute is hard-coded to expect files in these locations
- name: nova-compute hack for EDK2
  when: ansible_os_family == "RedHat"
  file: path=/usr/share/AAVMF state=directory
- name: nova-compute hack for EDK2
  when: ansible_os_family == "RedHat"
  file: src={{item.src}} dest={{item.dest}} state=link
  with_items:
    - src: /usr/share/edk2/aarch64/QEMU_EFI-pflash.raw
      dest: /usr/share/AAVMF/AAVMF_CODE.fd
    - src: /usr/share/edk2/aarch64/vars-template-pflash.raw
      dest: /usr/share/AAVMF/AAVMF_VARS.fd

# configure libvirtd to allow VM migration
- name: Copy /etc/default/libvirtd
  copy: src=default-libvirtd dest=/etc/default/libvirtd
  notify: restart-libvirtd

- name: Configure libvirtd
  template: src=libvirtd.conf dest=/etc/libvirt/libvirtd.conf
  notify: restart-libvirtd

- name: Ensure compute services are enabled and running
  service: name={{item}} enabled=true state=started
  with_items:
    - libvirtd
    - virtlogd
    - erp-nova-compute
    - erp-neutron-openvswitch-agent

- include: virsh-secret.yml client=nova virsh_uuid={{nova_ceph_virsh_uuid}}
- include: virsh-secret.yml client=cinder virsh_uuid={{cinder_ceph_virsh_uuid}}
