- name: Copy the secret {{client}}.xml needed by virsh
  template: src={{client}}-ceph.xml dest=/etc/nova/

- name: Obtain secret value from ceph config for {{client}}
  shell: cat /etc/ceph/ceph.client.{{client}}.keyring | grep "key =" | sed -e 's/.*key = //'
  changed_when: false
  register: ceph_secret

- name: Check if ceph key is defined in virsh
  command: virsh secret-list
  changed_when: false
  register: virsh_secret

- name: Define the ceph secret
  when: "virsh_secret is defined and '{{virsh_uuid}}' not in virsh_secret.stdout"
  command: virsh secret-define --file /etc/nova/{{client}}-ceph.xml

- name: Set initial value of the secret (for first time run)
  when: "virsh_secret is defined and '{{virsh_uuid}}' not in virsh_secret.stdout"
  command: virsh secret-set-value --secret {{virsh_uuid}} --base64 {{ceph_secret.stdout}}

- name: Check the value of the secret
  when: "virsh_secret is defined and '{{virsh_uuid}}' in virsh_secret.stdout"
  command: virsh secret-get-value --secret {{virsh_uuid}}
  changed_when: false
  ignore_errors: yes
  register: virsh_secret

- name: Update the secret
  when: "virsh_secret is defined and ceph_secret is defined
         and '{{virsh_secret.stdout}}' != '{{ceph_secret.stdout}}'"
  command: virsh secret-set-value --secret {{virsh_uuid}} --base64 {{ceph_secret.stdout}}
