- name: Enable Linaro Ceph overlay
  apt_repository: repo="deb http://repo.linaro.org/ubuntu/leg-ceph jessie main" state=present

- name: Install Ceph
  apt: pkg=ceph state=installed

- name: Copy ceph.conf
  template: src=ceph.conf dest=/etc/ceph/

- name: Copy keyring files
  template: src=keyring dest=/etc/ceph/ceph.client.{{item.name}}.keyring
  with_items:
    - {name: "admin", pass: "{{ceph_admin_pass}}", caps: []}
    - {name: "bootstrap-osd", pass: "{{ceph_bootstrap_osd_pass}}",
       caps: ['mon = "allow profile bootstrap-osd"']
      }
    - {name: "images", pass: "{{ceph_glance_pass}}",
       caps: [
         'mon = "allow r"',
         'osd = "allow class-read object_prefix rbd_children, allow rwx pool=images"'
       ]
      }
    - {name: "nova", pass: "{{ceph_nova_pass}}",
       caps: [
         'mon = "allow r"',
         'osd = "allow class-read object_prefix rbd_children, allow rwx pool=vms, allow rwx pool=images"'
       ]
      }
    - {name: "cinder", pass: "{{ceph_cinder_pass}}",
       caps: [
         'mon = "allow r"',
         'osd = "allow class-read object_prefix rbd_children, allow rwx pool=images"'
       ]
      }

- {include: osd.yml, with_items: "{{ceph_host_osds}}",
   when: "inventory_hostname not in ceph_mons"}
- {include: mon.yml,
   when: "inventory_hostname in ceph_mons"}
