- name: Create monitor key
  template: src=monitor_keyring dest=/etc/ceph/ceph.mon.{{ inventory_hostname }}.keyring

- name: Ceph monitor mkfs with keyring
  command: ceph-mon --cluster ceph --setuser ceph --setgroup ceph --mkfs -i {{ inventory_hostname }} --fsid {{ ceph_fsid }} -f -d
  args:
    creates: /var/lib/ceph/mon/ceph-{{ inventory_hostname }}/keyring

- name: Ensure the monitor is enabled and running
  service: name=ceph-mon@{{ inventory_hostname }} enabled=yes state=started

# You need a quorum to start defining users and pools. In our case this means
# 2 of 3 MONs should be onlined. Which means we shouldn't try to do this on
# the first MON we deploy (the data_host).
- include: configure_mon.yml
  when: inventory_hostname != data_host
