- include: roles/common/deploy_pkg.yml pkg_name={{neutron_pkg}}

- name: Setup neutron service
  openstack_service: user={{neutron_user}} password={{neutron_pass}} type=network
                     description="OpenStack Networking Service"
                     url="{{neutron_private_api}}"
                     public_url="{{neutron_public_api}}"
                     admin_password={{keystone_admin_pass}}
                     keystone_url="{{keystone_private_api}}"

- name: Add neutron database
  mysql_db: name=neutron state=present
            login_host={{mysql_host}} login_user={{mysql_root_user}} login_password={{mysql_root_pass}}

- name: Add neutron DB user
  mysql_user: name={{neutron_db_user}} password={{neutron_db_pass}} priv=neutron.*:ALL state=present
              host=% login_host={{mysql_host}} login_user={{mysql_root_user}} login_password={{mysql_root_pass}}

- name: Configure neutron.conf
  template: src=neutron.conf dest=/etc/neutron/neutron.conf
  notify: restart-neutron-service

- name: Run DB sync
  when: pkg_changed.changed
  command: /srv/neutron/bin/neutron-db-manage --config-file /etc/neutron/neutron.conf
           upgrade head

- name: Ensure neutron service is enabled and running
  service: name=erp-neutron-server enabled=yes state=started
