- include_vars: "{{ansible_os_family}}.yml"

- name: Install chrony for NTP
  package: name=chrony state=present

- name: Ensure daemon is enabled
  service: name={{chrony_daemon}} enabled=true state=started

- name: Configure chrony (ntp)
  copy: src=chrony.conf dest={{chrony_conf}}
  notify:
    - restart-chrony
