- include: roles/common/deploy_pkg.yml pkg_name={{nova_pkg}}

- name: Setup nova service
  openstack_service: user={{nova_user}} password={{nova_pass}} type=compute
                     description="OpenStack Compute Service"
                     url="{{nova_private_api}}"
                     public_url="{{nova_public_api}}"
                     admin_password={{keystone_admin_pass}}
                     keystone_url="{{keystone_private_api}}"

- name: Add nova database
  mysql_db: name=nova state=present
            login_host={{mysql_host}} login_user={{mysql_root_user}} login_password={{mysql_root_pass}}

- name: Add nova DB user
  mysql_user: name={{nova_db_user}} password={{nova_db_pass}} priv=nova.*:ALL state=present
              host=% login_host={{mysql_host}} login_user={{mysql_root_user}} login_password={{mysql_root_pass}}

- name: Add nova-api database
  mysql_db: name=nova-api state=present
            login_host={{mysql_host}} login_user={{mysql_root_user}} login_password={{mysql_root_pass}}

- name: Add nova-api DB user
  mysql_user: name={{nova_api_db_user}} password={{nova_api_db_pass}} priv=nova-api.*:ALL state=present
              host=% login_host={{mysql_host}} login_user={{mysql_root_user}} login_password={{mysql_user_root_pass}}

- name: Configure nova.conf
  template: src=nova.conf dest=/etc/nova/nova.conf
  notify: restart-nova-services

- name: Run DB sync
  when: pkg_changed.changed
  command: /srv/nova/bin/nova-manage db sync

- name: Run API DB sync
  when: pkg_changed.changed
  command: /srv/nova/bin/nova-manage api_db sync
