# TODO secure mysql and rabbit

- name: Install rabbitmq
  apt: pkg={{item}} state=installed
  with_items:
    - rabbitmq-server

- name: Configure an OpenStack Rabbit user
  rabbitmq_user: user={{rabbit_user}} password={{rabbit_pass}} vhost=/
                 configure_priv=.* read_priv=.* write_priv=.* state=present
