# TODO secure rabbit

- name: Install rabbitmq
  package: name=rabbitmq-server state=present

- name: Ensure daemon is enabled
  service: name=rabbitmq-server enabled=true state=started

- name: Configure an OpenStack Rabbit user
  rabbitmq_user: user={{rabbit_user}} password={{rabbit_pass}} vhost=/
                 configure_priv=.* read_priv=.* write_priv=.* state=present
