- name: restart-nova-services
  service: name={{item}} state=restarted
  with_items:
    - erp-nova-api
    - erp-nova-consoleauth
    - erp-nova-scheduler
    - erp-nova-conductor
    - erp-nova-cert
