- include_vars:"{{ ansible_os_family }}.yml"

- name: Install dependencies
  apt: name={{item}} state=present
  with_items: "{{ cinder_volume_deps }}"

- include: roles/common/deploy_venv.yml component=cinder notify=restart-cinder-volume
           url={{cinder_venv_url}} checksum={{cinder_venv_checksum}}

# python-ceph can't really be built into venv (and doesn't exist in pip)
# so symlink in what cinder-volume needs
- name: Hack symlinks for python-ceph into cinder venv
  file: src={{item}}
        dest=/srv/cinder/lib/python2.7/site-packages/{{item.split('/'[-1])}} state=link
  with_items: "{{ceph_python_libs}}"
  notify:
    - restart-cinder-volume

- name: Configure cinder.conf
  template: src=cinder.conf dest=/etc/cinder/
  notify: restart-cinder-volume
