- name: Setup cinder v1
  openstack_service: user={{cinder_user}} password={{cinder_pass}} type=volume
                     description="OpenStack Block Storage"
                     url="{{cinder_private_api}}"
                     public_url="{{cinder_public_api}}"
                     admin_password={{keystone_admin_pass}}
                     keystone_url="{{keystone_private_api}}"

- name: Setup cinder v2
  openstack_service: user={{cinder_user}} password={{cinder_pass}} type=volumev2
                     description="OpenStack Block Storage" service="cinderv2"
                     url="{{cinder_private_api_v2}}"
                     public_url="{{cinder_public_api_v2}}"
                     admin_password={{keystone_admin_pass}}
                     keystone_url="{{keystone_private_api}}"

- name: Add cinder DB
  mysql_db: name=cinder state=present
            login_host={{mysql_host}} login_user={{mysql_root_user}} login_password={{mysql_root_pass}}

- name: Add cinder DB user
  mysql_user: name={{cinder_db_user}} password={{cinder_db_pass}} priv=cinder.*:ALL state=present
              host=% login_host={{mysql_host}} login_user={{mysql_root_user}} login_password={{mysql_root_pass}}

- include: roles/common/deploy_venv.yml component=cinder notify=restart-cinder
           url={{cinder_venv_url}} checksum={{cinder_venv_checksum}}

- name: Configure cinder.conf
  template: src=cinder.conf dest=/etc/cinder/
  notify: restart-cinder

- name: Run DB sync
  when: venv.changed
  command: /srv/cinder/bin/cinder-manage db sync
