- name: Configure the data node
  hosts: "{{data_host}}"
  become: yes
  vars_files:
    - ["secrets/deployment-vars", "deployment-vars.example"]
    - ["secrets/host_vars/{{inventory_hostname}}", "vars/empty"]
  roles:
    - {role: ntp, tags: [ntp]}
    - {role: data, tags: [data]}
    - {role: zabbix-agent, tags: [zabbix-agent]}

- name: Configure the controller node
  hosts: "{{controller_host}}"
  become: yes
  vars_files:
    - ["secrets/deployment-vars", "deployment-vars.example"]
    - ["secrets/host_vars/{{inventory_hostname}}", "vars/empty"]
  roles:
    - {role: ntp, tags: [ntp]}
    - {role: cli, tags: [cli]}
    - {role: keystone, tags: [keystone]}
    - {role: glance, tags: [glance]}
    - {role: nova, tags: [nova]}
    - {role: neutron, tags: [neutron]}
    - {role: cinder, tags: [cinder]}
    - {role: horizon, tags: [horizon]}
    - {role: heat, tags: [heat]}
    - {role: zabbix-agent, tags: [zabbix-agent]}

- name: Configure the network node
  hosts: "{{network_host}}"
  become: yes
  vars_files:
    - ["secrets/deployment-vars", "deployment-vars.example"]
    - ["secrets/host_vars/{{inventory_hostname}}", "vars/empty"]
  roles:
    - {role: ntp, tags: [ntp]}
    - {role: nics, tags: [nics]}
    - {role: network, tags: [neutron]}
    - {role: zabbix-agent, tags: [zabbix-agent]}

- name: Configure the compute nodes
  hosts: "!{{data_host}}:!{{network_host}}:!{{controller_host}}:!{{zabbix_server}}"
  become: yes
  vars_files:
    - ["secrets/deployment-vars", "deployment-vars.example"]
    - ["secrets/host_vars/{{inventory_hostname}}", "vars/empty"]
  roles:
    - {role: ntp, tags: [ntp]}
    - {role: nics, tags: [nics]}
    - {role: compute, tags: [compute]}
    - {role: zabbix-agent, tags: [zabbix-agent]}

- name: Configure zabbix-server
#  hosts: "{{zabbix_server}}"
  hosts: zabbix_server
  vars_files:
    - ["secrets/deployment-vars", "deployment-vars.example"]
    - ["secrets/host_vars/{{inventory_hostname}}", "vars/empty"]
  become: yes
  roles:
    - {role: zabbix-server, tags: [zabbix-server]}
    - {role: zabbix-agent, tags: [zabbix-agent]}
