- name: restart-network-service
  service: name={{item}} enabled=true state=restarted
  with_items:
    - erp-neutron-l3-agent
    - erp-neutron-dhcp-agent
    - erp-neutron-metadata-agent
    - erp-neutron-openvswitch-agent
