- name: Setup Heat
  openstack_service: user={{heat_user}} password={{heat_pass}} type=orchestration
                     description="Orchestration"
                     url="{{heat_private_api}}"
                     public_url="{{heat_public_api}}"
                     admin_password={{keystone_admin_pass}}
                     keystone_url="{{keystone_private_api}}"

- name: Setup Heat Cloud Formation
  openstack_service: user={{heat_user}} password={{heat_pass}} type=cloudformation
                     description="Orchestration" service="heat-cfn"
                     url="{{heat_cfm_private_api}}"
                     public_url="{{heat_cfm_public_api}}"
                     admin_password={{keystone_admin_pass}}
                     keystone_url="{{keystone_private_api}}"

- name: Add heat database
  mysql_db: name=heat state=present
            login_host={{mysql_host}} login_user={{mysql_root_user}} login_password={{mysql_root_pass}}

- name: Add heat DB user
  mysql_user: name={{heat_db_user}} password={{heat_db_pass}} priv=heat.*:ALL state=present
              host=% login_host={{mysql_host}} login_user={{mysql_root_user}} login_password={{mysql_root_pass}}

- include: roles/common/deploy_venv.yml component=heat notify=restart-heat
           url={{heat_venv_url}} checksum={{heat_venv_checksum}}

- name: Configure heat.conf
  template: src=heat.conf dest=/etc/heat/
  notify: restart-heat

- name: Run DB sync
  when: venv.changed
  command: /srv/heat/bin/heat-manage db_sync

# TODO
# openstack domain create --description "Stack projects and users" heat
# openstack user create --domain heat --password {{heat_domain_pass}} {{heat_domain_admin}}
# openstack role add --domain heat --user-domain heat --user {{heat_domain_admin}} admin
# openstack role create heat_stack_owner
# openstack role create heat_stack_user
