- include_vars: "{{ansible_os_family}}.yml"

- name: Setup projects nic
  template: src={{projects_nic.src}} dest={{projects_nic.dest}} mode=0444
  register: projects_net

- name: Setup ext nic
  when: inventory_hostname in groups['networking_servers']
  template: src={{ext_nic.src}} dest={{ext_nic.dest}} mode=0444
  register: ext_net

- name: Bring up tunnel interface
  when: projects_net.changed
  command: ifup {{tunnel_interface}}

- name: Bring up public interface
  when: ext_net.changed
  command: ifup {{network_external_iface}}
